### ISSUE TITLE
Bug Report | Rock Paper Scissors game |Instead choosing  scissors it will then change to paper. 

### ISSUE THREAD

**Issue by jelumanao** [andreistalker/steemcasino#13]
#### Expected behavior
When you enter a game in Rock, Paper, Scissors game and choose scissors, it will display scissors.
Example:
Player A chose: Paper
Player B chose: Scissors

Player B win

#### Actual behavior
When you enter a game in Rock, Paper, Scissors game and choose scissors, it will then change to paper.
Player A chose: Paper
Player B chose: Scissors

It will become draw because scissors will change into Paper.

#### How to reproduce
*Device: ASUS X450CA
*Browser: Microsoft Edge Version 41.16299.248.0
*Browser: Google Chrome Version 65.0.3325.181
*Operating system: Windows 10 Home
*Internet Connection: PLDT HOME DSL

Use two different steemit accounts.

1. Open Microsoft Edge and load up steemcasino.org
2. Open Google Chrome and load up steemcasino.org
3. Log-in different accounts using Steemconnect. First account in Microsoft Edge and the second one is in Google chrome.
4. In steemcasino, click games and choose Rock, Paper, Scissors and execute the same  in the second account.
5. Use the second account to create a game and choose paper.
6. The first account will enter the game and choose scissors.

Expected result is, the 1st account will win the game, bug will occur, the scissors will change into paper which made the game draw. Refer to the video below.

#### Recording Of The Bug
https://youtu.be/QqhcxIrFUqs
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jemmanuel/bug-report-or-rock-paper-scissors-game-or-instead-choosing-scissors-it-will-then-change-to-paper">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by andreistalker** [comment]
Bug fixed in v0.0.7
