### ISSUE TITLE
Roulette doesn't work!

### ISSUE THREAD

**Issue by lonelywolf1** [andreistalker/steemcasino#14]
This is copy of my utopian contribution (link at the end)
#### The Site
SteemCasino Is a betting site for steem but It's now under bug testing, as the task request from the developer I come to the site and try my favorite betting way (roulette) and found that It does not work at all.

Task Request URL: [Here](https://utopian.io/utopian-io/@andreistalker/search-for-bugs-things-not-working-correctly)

#### Expected behavior
Roulette game should start when I bet or per round of the site.

#### Actual behavior
there is no timers, no last wins, no rounds and It's just not responding

#### How to reproduce
Make a timer for rounds, last round winners(number(s)) and make a roll animation.

* Browser: FireFox
* Operating system: Windows 10

#### Recording Of The Bug
https://www.youtube.com/watch?v=i_bqOF2lRiY&feature=youtu.be
(Mute the music, sorry)

(Link to utopian will be added in a few hours because of a utopian.io maintance)
if you find this useful please upvote my contribution :)

**Comment by andreistalker** [comment]
It was working, the bot was closed for maintenance. Try now.

**Comment by andreistalker** [comment]
And if it dosnt work please provide a screenshot of console. Right click->Inspect->Console
