### ISSUE TITLE
My Logo Contribution In utopian.io

### ISSUE THREAD

**Issue by rauljoe** [andreistalker/steemcasino#2]
Hello Author,
I have contribute a logo for SteemCasino
This is my logo contribution : 

![steemcasinoprev](https://user-images.githubusercontent.com/37005476/37708929-1930611c-2d3b-11e8-84a5-9bb1011e10d4.png)

This is the link : 
https://utopian.io/utopian-io/@rauljoe/logo-of-steem-casino-task-request

I hope you like it, Thanks :)

**Comment by ariefmunanzar** [comment]
Hello Author,
I have contribute a logo for SteemCasino
This is my logo contribution :
I hope you like it
![banner](https://user-images.githubusercontent.com/36419751/37734294-589ab590-2d7d-11e8-838d-7d1b464b8930.jpg)

**Comment by andreistalker** [comment]
Thanks for your contributions. They have been registred in our contest.
