### ISSUE TITLE
Propose Logo SteemCasino

### ISSUE THREAD

**Issue by mirzafuadigrafis** [andreistalker/steemcasino#4]
Hi, I would like to propose a logo for SteemCasino. I created a minimalist logo that can be used as profile picture, fav.ico and logo on website. The logo I created is simple, like your request. I hope you like it.
You can see other version on this [folder](https://drive.google.com/open?id=1gLIAm1b05Ye81WLuUUr_GfBhP5flBuUZ)
I will show completely other version/color if you request it. :)

![tampilan di open issue github](https://user-images.githubusercontent.com/37576772/37808766-b36c17dc-2e7e-11e8-93fa-74064f36bb27.png)

**Comment by andreistalker** [comment]
Thank you for your contribution!
