### ISSUE TITLE
Logo proposal for SteemCasino

### ISSUE THREAD

**Issue by ariefmunanzar** [andreistalker/steemcasino#5]
![banner](https://user-images.githubusercontent.com/36419751/37832423-22265bc2-2edb-11e8-9638-afd54832c49d.jpg)

Hi, I would like to propose a logo for SteemCasino. I created a minimalist logo that can be used as profile picture, fav.ico and logo on website. The logo I created is simple, like your request. I hope you like it.
You can see other version on this folder [here](https://drive.google.com/drive/folders/19caOrta_IJJDS2xqGzH_B523ueQFtATx?usp=sharing)
I will show completely other version/color if you request it. :)

**Comment by andreistalker** [comment]
Thank you for your contribution!
