### ISSUE TITLE
STEEM CASINO BUTTON DESIGN

### ISSUE THREAD

**Issue by berkorasen** [andreistalker/steemcasino#8]
Hi ı designed a few button for your task. 

![untitled-1](https://user-images.githubusercontent.com/37547531/38034124-45672760-32aa-11e8-8dc6-dd054d527138.jpg)
![untitled-2](https://user-images.githubusercontent.com/37547531/38034130-47e2911e-32aa-11e8-81d5-7c981e157c78.jpg)

**Comment by andreistalker** [comment]
Thank you for your contribution.
